{% set name = "anndata" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fac13140f425a393d24428b739d79bf91fcb9b83ec7cafeb1dd55718f44e914f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - typing_extensions
    # scverse-misc[settings] is present in the anndata pyproject.toml so we list the settings deps here
    - scverse-misc >=0.1.0
    - pydantic-settings
    - python-dotenv
    - python >={{ python_min }}
    - pandas >=2.3
    - scipy >=1.14,!=1.17.0
    - h5py >=3.11
    - numpy >=2.1
    - natsort
    - packaging >=24.2
    - array-api-compat >=1.7.1
    - zarr >=3.1
    - legacy-api-wrap
  run_constrained:
    - awkward >=2.3.2
    - xarray >=2025.06.1
    - dask >=2023.5.1,!=2024.8.*,!=2024.9.*,!=2025.2.*,!=2025.3.*,!=2025.4.*,!=2025.5.*,!=2025.6.*,!=2025.7.*,!=2025.8.*

test:
  imports:
    - anndata
  commands:
    - pip check
    - python -c "import anndata; print(anndata.__version__)"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/theislab/anndata
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An annotated data matrix.
  description: |
    AnnData provides a scalable way of keeping track of data and learned annotations.
    It was initially built for Scanpy (Genome Biology, 2018).
  doc_url: http://anndata.rtfd.io
  dev_url: https://github.com/theislab/anndata

extra:
  recipe-maintainers:
    - ilan-gold
    - jdblischak
    - jakakokosar
    - pavlin-policar
    - flying-sheep
    - ivirshup
