{% set name = "anndata" %}
{% set version = "0.12.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 50c89ac662d37b974dd61115b729e543cbe8c1f4358b4e4361763b8a08c724eb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - pandas >=2.1.0,!=2.1.2,<3
    - scipy >=1.12
    - h5py >=3.8
    - numpy >=1.26
    - natsort
    - packaging >=24.2
    - array-api-compat >=1.7.1
    - zarr >=2.18.7,!=3.0.*
    - legacy-api-wrap
  run_constrained:
    - awkward >=2.3.2
    - pyarrow <21
    - xarray >=2025.06.1
    - dask >=2023.5.1,!=2024.8.*,!=2024.9.*,!=2025.2.*,!=2025.3.*,!=2025.4.*,!=2025.5.*,!=2025.6.*,!=2025.7.*,!=2025.8.*

test:
  imports:
    - anndata
  commands:
    - pip check
    - python -c "import anndata; print(anndata.__version__)"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/theislab/anndata
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An annotated data matrix.
  description: |
    AnnData provides a scalable way of keeping track of data and learned annotations.
    It was initially built for Scanpy (Genome Biology, 2018).
  doc_url: http://anndata.rtfd.io
  dev_url: https://github.com/theislab/anndata

extra:
  recipe-maintainers:
    - ilan-gold
    - jdblischak
    - jakakokosar
    - pavlin-policar
    - flying-sheep
    - ivirshup
