{% set name = "anndata" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1f28f2c427e67b0b99bdd2b281717c92a12660dfd23e0694939b6e733f0eb2c4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - flit-core
    - setuptools_scm
    - pytoml
  run:
    - python >=3.8
    - pandas >=0.23.0
    - scipy >=1.4
    - h5py >=3.0
    - numpy >=1.16.5
    - natsort
    - packaging >=20

test:
  imports:
    - anndata
  commands:
    - pip check
    - python -c "import anndata; print(anndata.__version__)"
  requires:
    - pip

about:
  home: https://github.com/theislab/anndata
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An annotated data matrix.
  description: |
    AnnData provides a scalable way of keeping track of data and learned annotations. 
    It was initially built for Scanpy (Genome Biology, 2018).
  doc_url: http://anndata.rtfd.io
  dev_url: https://github.com/theislab/anndata

extra:
  recipe-maintainers:
    - jakakokosar
    - pavlin-policar
    - flying-sheep
    - ivirshup
