{% set name = "anndata" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b3f9c0272370ac6aa531bfcddd8904282997f90f596142999098c6e7f82965d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<35]

requirements:
  host:
    - python
    - pip
    - pathlib
    - setuptools_scm
  run:
    - python
    - pandas >=0.23.0
    - scipy
    - h5py
    - natsort
    - importlib_metadata  # [py<38]
    - packaging

test:
  imports:
    - anndata

about:
  home: https://github.com/theislab/anndata
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: An annotated data matrix.
  description: |
    AnnData provides a scalable way of keeping track of data and learned annotations. 
    It was initially built for Scanpy (Genome Biology, 2018).
  doc_url: http://anndata.rtfd.io
  dev_url: https://github.com/theislab/anndata

extra:
  recipe-maintainers:
    - jakakokosar
    - pavlin-policar
    - flying-sheep
